// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcbyjauevpniwtjbmdhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjYnlqYXVldnBuaXd0amJtZGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDg1NzYsImV4cCI6MjA1OTQyNDU3Nn0.BTLXlELTWwGxxn1ulzdvGlvLOqleDBKCdP-srgt15GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);